# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true      # comment out

# Setup
title:               To the backbone
tagline:             ""
description:         'This blog is a blog of Web engineer <a href="https://twitter.com/pinekta" target="_blank">@pinekta</a>. <br>Technical tips as well as things I felt in the development work are written.'
#url:                 ''
url:                 'https://blog.pinekta.tech'
baseurl:             ''
paginate:            10
twitter_username: pinekta
github_username:  pinekta

# About/contact
author:
  name:              pinekta
  url:               https://twitter.com/pinekta
  email:             h03a081b@gmail.com

# Gems
gems: [jekyll-paginate, jekyll-sitemap, jemoji]

# Custom vars
version:             1.0.0
